export PROJECT = suave
IMPORT_PATH := github.com/ehmad-kamal-99/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} ${DEV_IMAGE}

DOCKTEST := docker run --rm -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} --link suave-db:suave-db ${DEV_IMAGE}
